spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipes
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
  flyway:
    url: ${spring.datasource.url}
    user: user
    password: password

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

