version: '3.7'
services:
  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipes
    ports:
      - "5432:5432"
